DUT_NAME  = memory
RTL_FILES = ../rtl/src/*.sv
TB_FILES  = ../rtl/tb/$(DUT_NAME)_tb.sv
LIB_WORK  = lib_tb

run: libs compile
	vsim +nowarn3116 -voptargs=+acc -batch -l modelsim.log -do "run -all" $(LIB_WORK).$(DUT_NAME)_tb 

gui: libs compile
	vsim +nowarn3116 -voptargs=+acc -gui -l modelsim.log $(LIB_WORK).$(DUT_NAME)_tb &

waves:
	gtkwave waveform.vcd &	

compile:
	vlib ./$(LIB_WORK)
	vmap $(LIB_WORK) ./$(LIB_WORK) 
	vlog -work $(LIB_WORK) $(RTL_FILES) $(TB_FILES)

libs:
	mkdir -p ./$(LIB_WORK)

clean:
	rm -rf *.log
	rm -rf *.ini
	rm -rf *.vcd
	rm -rf *.wlf
	rm -rf transcript
	rm -rf ./$(LIB_WORK)
